### ISSUE TITLE
Codec not found 0

### ISSUE THREAD

**Issue by zheng59521** [illuspas/NodePlayer.js#13]
![image](https://user-images.githubusercontent.com/26600904/71910128-50536500-31ac-11ea-9c25-f5a32ea8d098.png)
代码是用的demo中的index.html,只是把我的ws地址修改了
为什么一直提示Codec not found 0?
看代码,引起Codec not found 0的地方是NodePlayer.js中
![image](https://user-images.githubusercontent.com/26600904/71910323-a4f6e000-31ac-11ea-8109-0232c861caa0.png)
的这里,
不明白为什么会一直提示Codec not found 0,求作者帮忙解答.

**Comment by illuspas** [comment]
是否是flv封装的流

**Comment by zheng59521** [comment]
> 是否是flv封装的流

感谢作者解答,是flv封装的流,现在已经解决了.原因是需要将流转格式为h264格式而我没有转格式
ffmpeg -re -i /dev/video0 -f flv  -vcodec libx264 rtmp:192.168.0.3:1935/live/v
