### ISSUE TITLE
H265 不能播放

### ISSUE THREAD

**Issue by songyu719** [illuspas/NodePlayer.js#2]
Assertion failed: flv->v.hevc.numOfArrays > 0, at: /Users/aliang/workspace/Emscripten/libmedia/libflv/source/flv-demuxer.c,203,flv_demuxer_video
Assertion failed: flv->v.hevc.numOfArrays > 0, at: /Users/aliang/workspace/Emscripten/libmedia/libflv/source/flv-demuxer.c,203,flv_demuxer_video

用以下命令 推流提示上面的错误 这可如何是好  用的Server 就是 Node-Media-Server
`ffmpeg -re -i rtmp://live.hkstv.hk.lxdns.com/live/hks -r 12  -g 60  -c:v libx265  -b:v 500k    -tune zerolatency -an  -f flv rtmp://192.168.1.7/live/hks`

**Comment by illuspas** [comment]
Node-Media-Server 用git版本，1.1.8版本有这个问题
