### ISSUE TITLE
H264+AAC 版本

### ISSUE THREAD

**Issue by thunderyan** [illuspas/NodePlayer.js#4]
Hi 能不能把 H264+AAC 版本也放出来一下，因为没有C++SourceCode，不能自行编译。
目前这个包对于前端应用来讲压缩到极致了也要2.9M，太大了。

**Comment by illuspas** [comment]
实际上是我低估了尺寸 😂  
不过需要的话，我隔天编译下

**Comment by notedit** [comment]
测试了这个库,  推送段用udp加速  然后播放端用nodeplayer  可以做到500ms以内的延迟.
希望能放出源码, 社区可以一起来维护, 做出一个能用在生产环境的版本.

**Comment by notedit** [comment]
i try to  compile openh264 use emscripten,  it is about 700k, not so small too.

**Comment by illuspas** [comment]
libopenh264.bc 作为库的时候，还是bitcode形式的，当链接为js时，编译器最终优化，会小很多

**Comment by illuspas** [comment]
这个我还没有尝试，近期较忙

**Comment by zhw2590582** [comment]
期待h264+aac版本
