### ISSUE TITLE
ios  native code implementation

### ISSUE THREAD

**Issue by alienmaster9** [illuspas/NodePlayer.js#5]
websocket player for ios native application development please give me a idea

**Comment by illuspas** [comment]
Why do you need websocket on ios? The live_flv over HTTP protocol is easy to implement.

**Comment by illuspas** [comment]
Why do you need websocket on ios native application development?   
The live_flv over HTTP protocol or rtmp is easy to implement.  
You can use this https://github.com/NodeMedia/NodeMediaClient-iOS

**Comment by quickstreamingmedia** [comment]
How about latency this is major concern

**Comment by illuspas** [comment]
If you use node-media-server as the server, and enable gop_cache.
NodeMediaClient-iOS player can open the video instantly.Delay in 1-2 seconds.

**Comment by quickstreamingmedia** [comment]
I will try keep you posted I close unwanted issues I will post here thank you so much for quick reply

**Comment by quickstreamingmedia** [comment]
13 seconds delay tested already this not acceptable
