### ISSUE TITLE
在苹果手机上播放没有声音

### ISSUE THREAD

**Issue by ikrong** [illuspas/NodePlayer.js#6]
`

	let np = new Module.NodePlayer();

	np.setPlayView('video');

	np.setScaleMode(1);

	np.enableVideo(true);

	np.enableAudio(true);

`

代码如上，在安卓和电脑上都有声音，就是苹果手机上没有，

iphone7  ios11.1-15B93

不知道，有没有遇到

**Comment by DricHao** [comment]
> `
> 
> ```
> let np = new Module.NodePlayer();
> 
> np.setPlayView('video');
> 
> np.setScaleMode(1);
> 
> np.enableVideo(true);
> 
> np.enableAudio(true);
> ```
> 
> `
> 
> 代码如上，在安卓和电脑上都有声音，就是苹果手机上没有，
> 
> iphone7 ios11.1-15B93
> 
> 不知道，有没有遇到

请问该问题您解决了吗

**Comment by ikrong** [comment]
> > `
> > ```
> > let np = new Module.NodePlayer();
> > 
> > np.setPlayView('video');
> > 
> > np.setScaleMode(1);
> > 
> > np.enableVideo(true);
> > 
> > np.enableAudio(true);
> > ```
> > 
> > 
> > `
> > 代码如上，在安卓和电脑上都有声音，就是苹果手机上没有，
> > iphone7 ios11.1-15B93
> > 不知道，有没有遇到
> 
> 请问该问题您解决了吗

当时是自己随便玩玩，用小程序和安卓手机搭建了一个简易的监控器，看我家小狗，后来就在电脑上看直播流了，就放弃苹果手机了。

**Comment by DricHao** [comment]
> > > `
> > > ```
> > > let np = new Module.NodePlayer();
> > > 
> > > np.setPlayView('video');
> > > 
> > > np.setScaleMode(1);
> > > 
> > > np.enableVideo(true);
> > > 
> > > np.enableAudio(true);
> > > ```
> > > 
> > > 
> > > `
> > > 代码如上，在安卓和电脑上都有声音，就是苹果手机上没有，
> > > iphone7 ios11.1-15B93
> > > 不知道，有没有遇到
> > 
> > 
> > 请问该问题您解决了吗
> 
> 当时是自己随便玩玩，用小程序和安卓手机搭建了一个简易的监控器，看我家小狗，后来就在电脑上看直播流了，就放弃苹果手机了。所以就没管这个问题.

所有程序都写完了，然后IOS端所有浏览器都没声音， 不得不放弃了
